name: 🏗️ Setup
description: Setup sources, pnpm, node and dependencies

inputs:
  ref:
    description: "Optional checkout ref"
  fetch-depth:
    description: "Optional checkout depth"

  pnpm_version:
    description: "Pnpm version to setup (will infer from package.json if blank)"
  node_version:
    description: "Node version to setup"

runs:
  using: composite
  steps:
    - name: ⛙ Checkout branch ${{ github.ref }}
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: 🏗️ Setup pnpm ${{ inputs.pnpm_version }}
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm_version }}

    - name: 🏗️ Setup Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    - name: 🧱 Install dependencies
      shell: bash
      run: |
        # ================ 🧱 install ================
        pnpm install
·